services:
  db:
    image: postgres:16
    container_name: credexp_db
    environment:
      POSTGRES_DB: credexp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: credexp_api
    depends_on:
      - db
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/credexp
      MLFLOW_TRACKING_URI: sqlite:////app/mlflow/mlflow.db
      MLFLOW_REGISTRY_URI: sqlite:////app/mlflow/mlflow.db
      MLFLOW_ARTIFACT_ROOT: /app/mlflow/artifacts
      MODEL_URI: models:/credit_scoring_model/Production
      PROMETHEUS_ENABLED: "true"
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: credexp_streamlit
    depends_on:
      - api
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/credexp
    command: ["uv", "run", "streamlit", "run", "streamlit_app/app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
    ports:
      - "8501:8501"

  prometheus:
    build:
      context: .
      dockerfile: docker/prometheus.Dockerfile
    container_name: credexp_prometheus
    depends_on:
      - api
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: credexp_grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data: