"""Start the service on the tracked artefacts, ask it three questions, and date the answer.

A frozen pipeline says nothing about itself: the last green tick is two years old, or gone
with the platform that drew it. ``reports/run-evidence.json`` is what stands in its place,
and it is written only when the run reproduces what is committed: the command, the day, the
revision, the versions installed, the seconds it took, and the file it compared.

**The comparison is the point.** If the three applicants come back scored differently from
`reports/serving_smoke.json`, nothing is written and the differing file is named. Evidence
that only says « it ran » proves a process started.

    uv run python scripts/smoke.py

Run it on a clean checkout, before the release tag. No workflow writes the evidence file: an
artefact regenerated by a machine on a schedule is an artefact nobody has read.
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version

from credexp.artifacts import write_json
from credexp.utils.paths import REPORTS_DIR, ROOT_DIR

EVIDENCE = "reports/run-evidence.json"
COMMAND = "uv run python scripts/smoke.py"

#: The one file this run rewrites, and the one it is compared against.
#:
#: It is the answer the shipped model gives three fixed applicants. Nothing else under
#: `reports/` can be regenerated from a clean clone: every other number rests on the Home
#: Credit holdout, which cannot be redistributed. What survives that restriction is the
#: deliverable itself, and this is the file that asks it a question.
KEY_OUTPUT: tuple[str, ...] = ("reports/serving_smoke.json",)

#: The distributions whose version changes the result. Not the whole lock file — the reader
#: needs what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = (
    "lightgbm",
    "scikit-learn",
    "numpy",
    "pandas",
    "fastapi",
    "joblib",
)

#: Three applicants, chosen to land on both sides of the threshold and to exercise the
#: imputation: two of the 796 columns are given, and the pipeline fills in the rest.
APPLICANTS = (
    {"sk_id_curr": 100001, "features": {"EXT_SOURCE_1": 0.9, "EXT_SOURCE_2": 0.9}},
    {"sk_id_curr": 100002, "features": {"EXT_SOURCE_1": 0.5, "EXT_SOURCE_2": 0.7}},
    {"sk_id_curr": 100003, "features": {"EXT_SOURCE_1": 0.02, "EXT_SOURCE_2": 0.05}},
)

BOOT_TIMEOUT = 180


def _free_port() -> int:
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def _get(url: str, timeout: float = 5.0) -> tuple[int, dict]:
    with urllib.request.urlopen(url, timeout=timeout) as answer:  # noqa: S310 - localhost
        return answer.status, json.loads(answer.read().decode("utf-8"))


def _post(url: str, payload: dict, timeout: float = 60.0) -> dict:
    request = urllib.request.Request(  # noqa: S310 - localhost
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=timeout) as answer:  # noqa: S310
        return json.loads(answer.read().decode("utf-8"))


def steps() -> None:
    """Start the service on the tracked artefacts, and ask it about three applicants.

    This is the whole of what a clean clone can run: the data is not redistributable, so
    every other published number rests on a file that is not here. What is here is the
    deliverable — a pipeline, a column order and a threshold — and the question worth asking
    it is whether it still answers what it answered.

    The service is started as a process rather than driven in memory, because the failures
    this is meant to catch live in the command: an entry point that no longer imports, an
    artefact missing from the tree, a startup event that raises.
    """
    port = _free_port()
    log = ROOT_DIR / "var" / "smoke-uvicorn.log"
    log.parent.mkdir(parents=True, exist_ok=True)
    environment = {
        **os.environ,
        "PYTHONIOENCODING": "utf-8",
        "MODEL_LOAD_MODE": "joblib",
        "MODEL_VERSION": "smoke",
        "PROMETHEUS_ENABLED": "false",
        # Nothing listens there, on purpose: the prediction log is best effort, and a smoke
        # run must not need a database to answer.
        "DATABASE_URL": "postgresql+psycopg://nobody:nobody@127.0.0.1:1/absent",
    }

    with log.open("w", encoding="utf-8") as handle:
        server = subprocess.Popen(  # noqa: S603 - fixed argv, no shell
            [
                sys.executable,
                "-m",
                "uvicorn",
                "credexp.serving.api:app",
                "--host",
                "127.0.0.1",
                "--port",
                str(port),
            ],
            cwd=str(ROOT_DIR),
            env=environment,
            stdout=handle,
            stderr=subprocess.STDOUT,
        )
        base = f"http://127.0.0.1:{port}"
        try:
            deadline = time.monotonic() + BOOT_TIMEOUT
            while time.monotonic() < deadline:
                if server.poll() is not None:
                    raise SystemExit(
                        f"uvicorn stopped with {server.returncode}:\n"
                        f"{log.read_text(encoding='utf-8', errors='replace')[-3000:]}"
                    )
                try:
                    status, _ = _get(f"{base}/health", timeout=2.0)
                except (urllib.error.URLError, OSError, TimeoutError):
                    time.sleep(0.5)
                    continue
                if status == 200:
                    break
            else:
                raise SystemExit(
                    "the service never answered /health:\n"
                    f"{log.read_text(encoding='utf-8', errors='replace')[-3000:]}"
                )

            _, info = _get(f"{base}/model-info")
            answers = []
            for applicant in APPLICANTS:
                body = _post(f"{base}/predict", applicant)
                answers.append(
                    {
                        "sk_id_curr": applicant["sk_id_curr"],
                        "features": applicant["features"],
                        # Rounded: the last digits of a float move between platforms, and a
                        # smoke run that failed on the sixteenth decimal would say nothing.
                        "proba_default": round(float(body["proba_default"]), 6),
                        "decision": int(body["decision"]),
                        "threshold": float(body["threshold"]),
                    }
                )
        finally:
            server.terminate()
            try:
                server.wait(timeout=20)
            except subprocess.TimeoutExpired:
                server.kill()

    if not any(answer["decision"] == 1 for answer in answers):
        raise SystemExit("no applicant was refused: the threshold is not being applied")

    write_json(
        REPORTS_DIR / "serving_smoke.json",
        {
            "what": "what the shipped artefacts answer for three fixed applicants",
            "n_applicants": len(answers),
            "model_name": info["model_name"],
            "n_features": info["n_features"],
            "threshold": info["threshold"],
            "answers": answers,
        },
    )


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (ROOT_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    if not KEY_OUTPUT:
        print("scripts/smoke.py: name the tracked files this run regenerates", file=sys.stderr)
        return 1

    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository are frozen to a manual trigger,
        # so there is no run to point at. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
